resolver: nightly-2018-08-15

packages:
  - .

extra-deps:
  - diagrams-graphviz-1.4
  - protolude-0.2.2
  - diagrams-lib-1.4.2.3
  - diagrams-svg-1.4.2
  - active-0.2.0.13
  - diagrams-core-1.4.1.1
  - dual-tree-0.2.2

allow-newer: true
